/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yeni kullanici kaydi (T-003) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Kullanici olusturuldu */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Bu e-posta zaten kayitli (EMAIL_ALREADY_REGISTERED). T-003 kriteri geregi `details` ALAN BAZLI doldurulur. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "EMAIL_ALREADY_REGISTERED",
                         *         "message": "Bu e-posta zaten kayitli.",
                         *         "details": [
                         *           {
                         *             "field": "email",
                         *             "message": "bu e-posta zaten kayitli"
                         *           }
                         *         ],
                         *         "traceId": "1f4c2b6a-9f2f-4d7d-8f2a-6c9b0a1d2e3f"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Giris yap, erisim token'i al (T-003) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Giris basarili */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description E-posta veya sifre hatali (INVALID_CREDENTIALS) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oturum sahibinin profili ve guncel abonelik durumu (T-003, T-012)
         * @description `subscription` alani HER ZAMAN doludur. Kullanicinin henuz bir abonelik satiri yoksa (satir ilk kez POST /billing/checkout ile olusur — architecture.md §8.3) varsayilan nesne doner: status = inactive, priceAmount = null, currency = SUBSCRIPTION_CURRENCY, currentPeriodEnd = null. Bu endpoint hicbir kosulda abonelik satiri OLUSTURMAZ.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profil */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hazir sablonlari listele — tam olarak 3 kayit (T-004) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sablon listesi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Template"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sablon secimini dogrula/getir (T-004) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: components["parameters"]["TemplateId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secilen sablon */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Template"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kendi tutanaklarini listele ve ara (T-011) */
        get: {
            parameters: {
                query?: {
                    /** @description Baslik veya not icinde gecen terim (bos birakilirsa filtre uygulanmaz) */
                    q?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Kullanicinin kendi tutanaklari, created_at DESC (eslesme yoksa bos liste) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportListResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Tutanak taslagi olustur (T-005) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReportRequest"];
                };
            };
            responses: {
                /** @description Taslak olusturuldu (status = draft) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Report"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description Belirtilen sablon bulunamadi (TEMPLATE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kendi tutanagini getir (T-005) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tutanak detayi (fotograflar dahil) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tutanagin fotograflarini damgalariyla listele (T-006) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fotograf listesi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Tutanaga fotograf ekle; damga sunucuda uretilir (T-006)
         * @description Yuklenen dosya sihirli bayt kontrolu ile dogrulanir (image/jpeg, image/png, image/webp). GOVDE KURALI (baglayici tek kural — basliktaki govde katiligi ISTISNA (1), architecture.md §7, CLAUDE.md §3.7): govdede `file` DISINDAKI TUM ALANLAR YOK SAYILIR; bu endpoint'te `forbidNonWhitelisted` UYGULANMAZ, ek alan 400 URETMEZ. `capturedAt` dahil hicbir istemci tarih degeri okunmaz; damga DB'de `DEFAULT now()` ile uretilir ve hicbir endpoint uzerinden degistirilemez (guncelleme/PATCH route'u TANIMLI DEGILDIR). T-006 kabul kriteri 3 bu davranisla dogrulanir: govdeye tarih alani eklenmis istek 201 + SUNUCU damgasi doner. SIRALAMA: `sort_order` sunucuda atanir (mevcut en buyuk + 1); istemci gonderemez. KANIT BUTUNLUGU (architecture.md §8.1, CLAUDE.md §3.10 — baglayici tek kural): reports.status = 'approved' ise yukleme REDDEDILIR (409 REPORT_ALREADY_APPROVED); `draft` ve `shared` durumlarinda yukleme serbesttir. Onay, tutanagin icerigini dondurur.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Maksimum 10 MB
                         */
                        file: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Fotograf eklendi */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
                /** @description Desteklenmeyen format, bozuk dosya veya boyut asimi (UNSUPPORTED_MEDIA_FORMAT / FILE_TOO_LARGE) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Iki durumdan biri: tutanak basina fotograf ust siniri (PHOTO_MAX_PER_REPORT = 30) asildi (PHOTO_LIMIT_REACHED) VEYA tutanak zaten onaylanmis oldugu icin icerigi dondurulmus (REPORT_ALREADY_APPROVED — architecture.md §8.1). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
                502: components["responses"]["StorageUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tutanagin PDF ciktisini uret ve indir (T-007, T-010)
         * @description PDF; baslik, sablon adi, not ve tum fotograflari kendi tarih-saat damgalariyla icerir. Tutanak onaylanmissa onay zaman damgasi ve onaylayan e-posta da PDF'e islenir (T-010).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF dosyasi */
                200: {
                    headers: {
                        /** @description attachment; filename="tutanak-<id>.pdf" */
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                /** @description Tutanakta hic fotograf yok, PDF uretilemez (REPORT_HAS_NO_PHOTOS) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                502: components["responses"]["StorageUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}/share-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tutanagin mevcut paylasim linkini getir (T-008) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mevcut paylasim linki */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareLink"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Bu tutanak icin henuz paylasim linki uretilmemis (SHARE_LINK_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Paylasim linki olustur (idempotan) (T-008)
         * @description Ayni tutanak icin ikinci kez cagrildiginda YENI token uretilmez; mevcut aktif link ayni token ile geri donulur. DURUM GECISI: bu cagri basarili oldugunda reports.status `draft` -> `shared` gecisini yapar (tutanak zaten `shared` veya `approved` ise durum DEGISMEZ). `shared` -> `approved` gecisi YALNIZCA onay kaydiyla olur; geri gecis yoktur.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paylasim linki (yeni uretilmis veya mevcut olan) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareLink"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}/share-link/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paylasim linkini e-posta ile gonder (T-008)
         * @description ON KOSUL (architecture.md §8.1, CLAUDE.md §3.10 — baglayici tek kural): bu endpoint paylasim linki URETMEZ; ilgili tutanak icin link yoksa 404 SHARE_LINK_NOT_FOUND doner — once POST /reports/{reportId}/share-link cagrilir. Boylece "linkin varligi durumu belirler" degismezi korunur ve bu endpoint reports.status'u DEGISTIRMEZ. Gonderim senkron yapilir; sonuc (sent/failed) yanitta acikca belirtilir. SAGLAYICI HATASI ISTISNA DEGILDIR: e-posta gonderilemezse de yanit 202'dir ve `status = failed` + `errorMessage` doner (502/ErrorEnvelope DONMEZ). Paylasim linkinin kendisi her durumda gecerli kalir.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendShareEmailRequest"];
                };
            };
            responses: {
                /** @description Gonderim denendi; sonuc yanitta */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareDelivery"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Tutanak bulunamadi (NOT_FOUND) VEYA tutanak icin henuz paylasim linki uretilmemis (SHARE_LINK_NOT_FOUND) — bu endpoint link uretmez. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/reports/{shareToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tutanagi paylasim linki ile, oturum acmadan goruntule (T-009, T-010)
         * @description Salt-okunur gorunum. Yanit, onay oncesi gosterilmesi zorunlu "resmi hukuki delil degildir, destekleyici kanittir" uyari metnini icerir (T-010). Bu endpoint hicbir yazma eylemi sunmaz.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shareToken: components["parameters"]["ShareToken"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Salt-okunur tutanak gorunumu */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicReportView"];
                    };
                };
                /** @description Gecersiz veya var olmayan paylasim token'i (SHARE_LINK_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/reports/{shareToken}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tek tikla onay (T-010)
         * @description Tutanak basina tek onay kaydi olusur; ikinci onay istegi 409 doner.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shareToken: components["parameters"]["ShareToken"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateApprovalRequest"];
                };
            };
            responses: {
                /** @description Onay kaydedildi (zaman damgasi + e-posta) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Approval"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Gecersiz paylasim token'i (SHARE_LINK_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Tutanak zaten onaylanmis (REPORT_ALREADY_APPROVED) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aylik abonelik odemesini baslat (T-012)
         * @description `payment_transactions` satiri da BURADA yazilir (status='initiated', provider_reference = transactionReference, processed_at = NULL — architecture.md §8.5); webhook bu satiri gunceller, yenisini yazmaz. Abonelik satiri ilk kez BURADA olusur (get-or-create, architecture.md §8.3) ve cagri basariyla dondugunde durum `pending` olur (architecture.md §8.4 — abonelik AKTIFE GECMEZ; aktiflesme yalnizca /billing/webhook `succeeded` ile olur). Tutar ve para birimi `SUBSCRIPTION_PRICE_AMOUNT` / `SUBSCRIPTION_CURRENCY` yapilandirmasindan gelir (CLAUDE.md §5.1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Odeme oturumu olusturuldu */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Abonelik zaten aktif (SUBSCRIPTION_ALREADY_ACTIVE) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Odeme saglayicisina ulasilamadi (PAYMENT_PROVIDER_ERROR) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Odeme saglayicisi bildirimi (T-012)
         * @description Saglayici imzasi dogrulanmadan hicbir abonelik durumu degismez. ISLEME MEKANIZMASI (architecture.md §8.5, CLAUDE.md §3.13 — baglayici tek kural): bu endpoint YENI `payment_transactions` satiri YAZMAZ; satir checkout'ta dogmustur. Bildirim, satiri `providerReference` ile bulup YALNIZCA `processed_at IS NULL` iken gunceller (`processed_at = now()`), abonelik gecisi ayni transaction'dadir. DURUM ETKISI (architecture.md §8.4): `succeeded` -> abonelik `active` + currentPeriodEnd = now() + SUBSCRIPTION_PERIOD_DAYS gun; `failed` -> `inactive` + currentPeriodEnd NULL; abonelik zaten `active` ise `failed` bildirimi durumu DUSURMEZ. GOVDE POLITIKASI (baglayici — basliktaki istisna (2)): govde saglayiciya aittir; bu route'ta `forbidNonWhitelisted` UYGULANMAZ, asagidaki semada olmayan alanlar sessizce ayiklanir ve 400 URETMEZ. ALAN ADI NORMALIZASYONU (architecture.md §8.5): imza dogrulamasi ve saglayici alan adlarinin asagidaki kanonik sekle cevrilmesi `PaymentPort.verifyAndParseNotification(rawBody, signature)` icinde, yani `IyzicoPaymentAdapter`'da yapilir; controller/service yalnizca kanonik sekli gorur. `PAYMENT_PROVIDER=fake` iken (yerel + QA) govde bu semayla BIREBIR gonderilir. Kimliksiz bir endpoint oldugu icin IP basina hiz siniri uygulanir (60 istek/dk/IP — architecture.md §7); asildiginda 429 doner.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-Iyzico-Signature": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentWebhookRequest"];
                };
            };
            responses: {
                /** @description Bildirim islendi (idempotan). AYNI YANIT uc durumda da donulur: (1) bildirim ilk kez islendi (abonelik durumu §8.4'e gore degisti); (2) ayni `providerReference` DAHA ONCE islenmis (processed_at dolu) — hicbir alan degismez, `currentPeriodEnd` yeniden HESAPLANMAZ; (3) `providerReference` TANINMIYOR (eslesen satir yok) — durum degismez, olay `warn` seviyesinde loglanir. Imza gecerliyken 4xx donmek saglayicinin bildirimi suresiz tekrarlamasina yol acacagi icin (2) ve (3) hata DEGILDIR. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Yalnizca ZORUNLU alanlar (providerReference, status) normalizasyondan sonra eksik/gecersizse doner (VALIDATION_ERROR). Ek/bilinmeyen alanlar 400 URETMEZ, sessizce ayiklanir; TANINMAYAN providerReference de 400 DEGIL 200'dur. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Imza dogrulanamadi (INVALID_WEBHOOK_SIGNATURE) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": {
         *         "code": "VALIDATION_ERROR",
         *         "message": "Girdi dogrulanamadi.",
         *         "details": [
         *           {
         *             "field": "title",
         *             "message": "baslik zorunludur"
         *           }
         *         ],
         *         "traceId": "1f4c2b6a-9f2f-4d7d-8f2a-6c9b0a1d2e3f"
         *       }
         *     }
         */
        ErrorEnvelope: {
            error: {
                /**
                 * @description Makine tarafindan okunabilir, stabil hata kodu
                 * @enum {string}
                 */
                code: "VALIDATION_ERROR" | "UNAUTHENTICATED" | "INVALID_CREDENTIALS" | "FORBIDDEN" | "NOT_FOUND" | "EMAIL_ALREADY_REGISTERED" | "TEMPLATE_NOT_FOUND" | "REPORT_HAS_NO_PHOTOS" | "UNSUPPORTED_MEDIA_FORMAT" | "FILE_TOO_LARGE" | "PHOTO_LIMIT_REACHED" | "SHARE_LINK_NOT_FOUND" | "REPORT_ALREADY_APPROVED" | "SUBSCRIPTION_ALREADY_ACTIVE" | "INVALID_WEBHOOK_SIGNATURE" | "STORAGE_UNAVAILABLE" | "PAYMENT_PROVIDER_ERROR" | "RATE_LIMIT_EXCEEDED" | "INTERNAL_ERROR";
                /** @description Son kullaniciya gosterilebilir Turkce aciklama (sir/stack icermez) */
                message: string;
                /** @description Alan bazli hatalar; `VALIDATION_ERROR` ve `EMAIL_ALREADY_REGISTERED` yanitlarinda DOLU, diger hata kodlarinda bos/yoktur. */
                details?: {
                    /** @example title */
                    field: string;
                    /** @example baslik zorunludur */
                    message: string;
                }[];
                /** @description Log korelasyon kimligi */
                traceId: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description JWT (HS256) */
            accessToken: string;
            /**
             * @description Saniye cinsinden gecerlilik
             * @example 604800
             */
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
            subscription: components["schemas"]["Subscription"];
        };
        Template: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            code: "move_in_out" | "meter_fixture" | "periodic_check";
            /** @example Giris/Cikis Teslim Tutanagi */
            name: string;
            description: string;
        };
        /**
         * @description Tek yonlu yasam dongusu: `draft` (olusturuldu) -> `shared` (POST /reports/{reportId}/share-link basariyla cagrildi) -> `approved` (karsi taraf POST /public/reports/{shareToken}/approval ile onayladi). Geri gecis YOKTUR; durumu dogrudan degistiren bir endpoint TANIMLI DEGILDIR.
         * @enum {string}
         */
        ReportStatus: "draft" | "shared" | "approved";
        CreateReportRequest: {
            /** Format: uuid */
            templateId: string;
            title: string;
            /** @default  */
            note: string;
        };
        Report: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            templateId: string;
            templateName: string;
            title: string;
            note: string;
            status: components["schemas"]["ReportStatus"];
            /** @description Her yanitta hesaplanir (liste ekrani icin) */
            photoCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReportDetail: components["schemas"]["Report"] & {
            photos: components["schemas"]["Photo"][];
            approval?: components["schemas"]["Approval"];
        };
        ReportListResponse: {
            /** @description created_at DESC siralamasinda, yalnizca oturum sahibinin kayitlari */
            items: components["schemas"]["Report"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Photo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reportId: string;
            /**
             * Format: date-time
             * @description Sunucu tarafinda uretilen, DEGISTIRILEMEZ tarih-saat damgasi (T-006)
             */
            capturedAt: string;
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
            widthPx: number;
            heightPx: number;
            /**
             * Format: uri
             * @description Obje depolamadan uretilmis, kisa omurlu (15 dk) on-imzali okuma URL'si
             */
            url: string;
        };
        ShareLink: {
            /** @description 32 bayt entropiden uretilmis base64url deger */
            token: string;
            /**
             * Format: uri
             * @example https://app.example.com/t/AbC...
             */
            url: string;
            /**
             * Format: uri
             * @description Onceden doldurulmus wa.me URL'si
             */
            whatsAppUrl: string;
            /** Format: date-time */
            createdAt: string;
        };
        SendShareEmailRequest: {
            /** Format: email */
            recipientEmail: string;
        };
        ShareDelivery: {
            /** Format: uuid */
            id: string;
            /**
             * @description MVP'de TEK kanal: e-posta. Teslim kaydi yalnizca SUNUCUNUN yaptigi gonderim icin yazilir; WhatsApp paylasimi sunucudan gonderim degil, istemcinin actigi bir wa.me URL'sidir (ShareLink.whatsAppUrl) ve teslim kaydi URETMEZ.
             * @enum {string}
             */
            channel: "email";
            /** Format: email */
            recipientEmail: string;
            /** @enum {string} */
            status: "sent" | "failed";
            /** @description status = failed ise DOLU */
            errorMessage?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PublicReportView: {
            title: string;
            templateName: string;
            note: string;
            photos: components["schemas"]["PublicPhoto"][];
            status: components["schemas"]["ReportStatus"];
            /** Format: date-time */
            createdAt: string;
            isApproved: boolean;
            approval?: components["schemas"]["Approval"];
            /**
             * @description Onay oncesi zorunlu uyari metni (T-010)
             * @example Bu tutanak resmi hukuki delil degildir, destekleyici kanittir.
             */
            disclaimer: string;
        };
        PublicPhoto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            capturedAt: string;
            /** Format: uri */
            url: string;
        };
        CreateApprovalRequest: {
            /** Format: email */
            approverEmail: string;
        };
        Approval: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            approverEmail: string;
            /**
             * Format: date-time
             * @description Sunucu tarafinda uretilen, degistirilemez onay damgasi
             */
            approvedAt: string;
        };
        Subscription: {
            /**
             * @description DoD'deki "aktif/pasif" gosterimi. GECIS KURALI (architecture.md §8.4, CLAUDE.md §3.12 — baglayici tek kural): POST /billing/checkout basarili oldugunda `inactive` (ya da yeni olusturulmus satir) -> `pending`; webhook `succeeded` -> `active` (+ currentPeriodEnd yazilir); webhook `failed` -> `inactive` (currentPeriodEnd NULL birakilir); durum `active` iken gelen `failed` bildirimi durumu DUSURMEZ. Istemci uc degeri de render eder; `pending` = "odeme sonucu bekleniyor, abonelik henuz aktif degil".
             * @enum {string}
             */
            status: "inactive" | "pending" | "active";
            /**
             * @description Ondalikli para degeri metin olarak (numeric); kayan noktali sayi KULLANILMAZ. Odeme baslatildiginda `SUBSCRIPTION_PRICE_AMOUNT` degerinden yazilir.
             * @example 199.00
             */
            priceAmount?: string | null;
            /** @example TRY */
            currency: string;
            /**
             * Format: date-time
             * @description Yalnizca `active` durumda doludur (DB CHECK: subscriptions_active_needs_period). Deger webhook `succeeded` islenirken SUNUCUDA hesaplanir: now() + `SUBSCRIPTION_PERIOD_DAYS` gun (CLAUDE.md §5.1, varsayilan 30). Saglayici bildiriminden OKUNMAZ ve koda gomulmez.
             */
            currentPeriodEnd?: string | null;
        };
        CheckoutResponse: {
            /** @description Saglayicidaki islem referansi. `payment_transactions.provider_reference` sutununa BIREBIR bu deger yazilir ve webhook idempotans anahtari budur (architecture.md §8.5). */
            transactionReference: string;
            /**
             * Format: uri
             * @description Kullanicinin yonlendirilecegi odeme sayfasi
             */
            checkoutUrl: string;
            /**
             * @description Ondalikli para degeri METIN olarak. Kaynagi `SUBSCRIPTION_PRICE_AMOUNT` yapilandirmasidir (CLAUDE.md §5.1); kod icine sabit tutar gomulmez ve deger float'a parse EDILMEZ.
             * @example 199.00
             */
            amount: string;
            /**
             * @description Kaynagi `SUBSCRIPTION_CURRENCY` yapilandirmasidir (varsayilan TRY).
             * @example TRY
             */
            currency: string;
        };
        /** @description Saglayici bildiriminin KANONIK (normalize edilmis) sekli. Bilincli olarak DONEM BILGISI TASIMAZ: `currentPeriodEnd` sunucuda `SUBSCRIPTION_PERIOD_DAYS` ile hesaplanir (architecture.md §8.4). Gercek saglayici govdesindeki alan adlari bu sekle `IyzicoPaymentAdapter` icinde cevrilir; ek alanlar 400 URETMEDEN yok sayilir (basliktaki istisna (2), CLAUDE.md §3.7) — bu yuzden sema `additionalProperties: false` DEGILDIR. Imza dogrulamasi HAM govde uzerinde yapilir (`NestFactory.create(..., { rawBody: true })`, CLAUDE.md §1). */
        PaymentWebhookRequest: {
            /** @description Idempotans anahtari (payment_transactions.provider_reference) */
            providerReference: string;
            /** @enum {string} */
            status: "succeeded" | "failed";
            /** @description status = failed oldugunda DB CHECK'i (payment_transactions_failed_needs_reason) geregi bir neden gereklidir; saglayici neden gondermezse sunucu sabit bir varsayilan neden metni yazar (bilgi kaybi olmadan, "saglayici neden bildirmedi"). */
            failureReason?: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Girdi dogrulama hatasi (VALIDATION_ERROR) — alan bazli detaylar `details` icinde */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Token yok, gecersiz veya suresi dolmus (UNAUTHENTICATED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Kaynak baska bir kullaniciya ait (FORBIDDEN) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Kaynak bulunamadi (NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Hiz siniri asildi (RATE_LIMIT_EXCEEDED) */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Obje depolamaya (R2/MinIO) ulasilamadi (STORAGE_UNAVAILABLE). Yukleme basarisizsa DB'ye satir YAZILMAZ; okuma basarisizsa yarim PDF URETILMEZ. */
        StorageUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ReportId: string;
        TemplateId: string;
        ShareToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
